version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb+srv://harshkr2709:l0iolqd3F8cZfDB7@cluster0.ipsxs.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
